apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mysecret
  namespace: default
spec:
  encryptedData:
    foo: AgBqo1dXDYBTgqzYCm+wMh0JE2zovXmI4LeXIgjsW8NEUhHDXbhV56GN8g8DTEbIXTmu4JwBeydAs3VkZYeTIyk59Zo+5qY+xRb9RHdwGdUJ2Osl3cydJjGGWnao08gMLbFxO5xZcbdOI0fJEFs36MT4S4ExsN/IKK537fVQOj0N2nq02PXbsVLcF9y8Yovws/9ksaup148Ul5WObdZFrLR5KYDxsVn7h2gPfQfNiYvSbS5URB6TDKIrVlCGhRb+T9i8T4J6amXs0xSprL7iQRASfWLGWtJoij9x6gAOogiJnLF7H5E3EYayiz+EOOapO8faSx4yf/fxfGMqR55XSe4nFEV2QvhDF/ZtJsb/kBrFtFZzv8Qluvke4Cc+1Zk0zsEhC2h/zveyaWhIhyLcNmqTgQHwwlecpi40Zlx7VgqCE31WvWulHZ6vtF5yll12PDtsyoRPDNFB5vRBkBxuaSZBYXk/Jec6bqP2V8zYVcQ+LhNN1jLE23/A9sI/MB1VmLq0CYF/dbQdZ9RGsQ0ddzVeyAvzNN9qPTsDlGM9uUGMW4Yflk3qWOVH7YF4fDYDyemzPl9kFiM3NzBZ05hRbB5Rqb63jK/ezJrbPEbnWX238syCa1MYxLo3apZu8lWjNpd9/ap3tQJzkv06lz/gINAHypNx+eqvEn6gwu90rmU4FWSHARgYnaUlOdOkY2KebxJsgvM=
  template:
    metadata:
      creationTimestamp: null
      name: mysecret
      namespace: default

