apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: first-vela-app
spec:
  components:
    - name: express-server
      type: webservice
      properties:
        image: kong/httpbin
        ports:
         - port: 80
           expose: false
      traits:
        - type: scaler
          properties:
            replicas: 1
  # policies:
  #   - name: target-default
  #     type: topology
  #     properties:
  #       # The cluster with name local is installed the KubeVela.
  #       clusters: ["local"]
  #       namespace: "production"
  # workflow:
  #   steps:
  #     - name: deploy2default
  #       type: deploy
  #       properties:
  #         policies: ["target-default"]
