apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: first-vela-app-2
spec:
  components:
  - name: first-vela-app-2
    type: kustomize
    properties:
      repoType: git
      # replace it with your repo url
      url: https://github.com/obrin/crossplane-sandbox
      # replace it with your git secret if it's a private repo
      # secretRef: git-secret
      # the pull interval time, set to 10m since the infrastructure is steady
      pullInterval: 5m
      git:
        # the branch name
        branch: main
      # the path to sync
      path: ./app